name: Re-usable Release Flow
on:
  workflow_call:

jobs:
  resources:
    name: Update wp plugin version
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6

        - uses: actions/setup-node@v6

        - name: Install dependencies
          run: sudo pip3 install PyGithub

        - name: Get the python File
          uses: actions/checkout@v6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            repository: tsjippy/shared-functionality
            path: scripts
            sparse-checkout: |
              .github/workflows/update_version.py
            sparse-checkout-cone-mode: false

        - name: Update version
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            RELEASE_TAG: ${{ github.event.release.name }}
            PLUGIN: ${{ github.event.repository.name }}
          run: python scripts/.github/workflows/update_version.py

        - name: Set Prefix
          id: prefix
          run: |
            if [[ ${{ github.event.repository.name }} =~ "tsjippy-" ]]; then
              echo "prefix=" >> "$GITHUB_OUTPUT"
            else
              echo "prefix=tsjippy-" >> "$GITHUB_OUTPUT"
            fi

        - name: Commit version update
          uses: test-room-7/action-update-file@v2
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              allow-removing: true
              file-path: |
                CHANGELOG.md
                {${{ steps.prefix.outputs.prefix }}${{ github.event.repository.name }}.php,style.css}
              commit-msg: Update wp plugin version
              github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: WP Release
          run: zip -r ${{ steps.prefix.outputs.prefix }}${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "scripts/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "signalbot.db" "SignalBot.py" "CHANGELOG.md" "README.md" "*.code-workspace" "*.cmd" ".vscode" "test.php"
        
        - name: DEV Release
          run: zip -r dev-${{ steps.prefix.outputs.prefix }}${{ github.event.repository.name }}.zip . -x "scripts/*"

        - name: Release
          uses: softprops/action-gh-release@v3
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: | 
              ${{ steps.prefix.outputs.prefix }}${{ github.event.repository.name }}.zip
              dev-${{ steps.prefix.outputs.prefix }}${{ github.event.repository.name }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}